name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.backend
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/ddice-backend:latest
          ${{ secrets.DOCKER_USERNAME }}/ddice-backend:${{ github.sha }}

    - name: Deploy to Kubernetes
      uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Update Deployment
      run: |
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl set image deployment/backend-deployment backend=${{ secrets.DOCKER_USERNAME }}/ddice-backend:${{ github.sha }}
        kubectl rollout status deployment/backend-deployment